#!/usr/bin/env bash
# =====================================================================
# scripts/build-extension.sh — 一键构建 Chrome 扩展
#
# 步骤：
#   1. 装 deps（如缺）
#   2. 自动从 api/.env.local 派生 extension/.env.production
#   3. plasmo build → build/chrome-mv3-prod/
#   4. 输出 ZIP 路径 + 上传到 CWS 的提示
#
# 用法：
#   bash scripts/build-extension.sh           # 默认构建
#   bash scripts/build-extension.sh --target=firefox-mv2
#   bash scripts/build-extension.sh --zip     # 额外生成 zip
# =====================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

EXT_DIR="extension"
ROOT="$(pwd)"
API_ENV="api/.env.local"
EXT_ENV="$EXT_DIR/.env.production"

# ----- args -----
TARGET="chrome-mv3"
ZIP_AFTER=0
for arg in "$@"; do
  case "$arg" in
    --target=*) TARGET="${arg#--target=}" ;;
    --zip)      ZIP_AFTER=1 ;;
    --help|-h)
      sed -n '2,15p' "$0"
      exit 0 ;;
    *) echo "unknown flag: $arg"; exit 1 ;;
  esac
done

echo "============================================="
echo "  Build Chrome Extension"
echo "  Target: $TARGET"
echo "============================================="

# ----- 1. deps -----
if [ ! -d "$EXT_DIR/node_modules/plasmo" ]; then
  echo
  echo "→ installing extension deps..."
  (cd "$EXT_DIR" && npm install --no-audit --no-fund --prefer-offline)
else
  echo "✓ deps already installed"
fi

# ----- 1.5. apply node_modules patches -----
# Plasmo 0.86 has 4 known issues that need patching after every npm install.
# Idempotent — safe to run on every build.
bash "$ROOT/scripts/patch-node-modules.sh" || exit 1

# ----- 2. .env.production -----
if [ -f "$EXT_ENV" ]; then
  echo "✓ $EXT_ENV exists"
else
  echo "→ creating $EXT_ENV from $API_ENV"
  if [ ! -f "$API_ENV" ]; then
    echo "✗ $API_ENV not found. Please create it first."; exit 1
  fi
  # Extract Supabase URL + anon key from api/.env.local
  SUPABASE_URL=$(grep '^SUPABASE_URL=' "$API_ENV" | head -1 | cut -d= -f2)
  SUPABASE_ANON_KEY=$(grep '^SUPABASE_ANON_KEY=' "$API_ENV" | head -1 | cut -d= -f2)
  API_BASE_URL=$(grep '^NEXT_PUBLIC_SITE_URL=' "$API_ENV" | head -1 | cut -d= -f2)

  if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
    echo "✗ SUPABASE_URL or SUPABASE_ANON_KEY missing in $API_ENV"; exit 1
  fi

  cat > "$EXT_ENV" <<EOF
# Auto-generated by scripts/build-extension.sh on $(date)
PLASMO_PUBLIC_API_BASE_URL=${API_BASE_URL:-http://localhost:3000}
PLASMO_PUBLIC_SUPABASE_URL=$SUPABASE_URL
PLASMO_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
EOF
  echo "  → wrote $EXT_ENV:"
  sed 's/^/    /' "$EXT_ENV"
fi

# ----- 2.5. generate Plasmo's gen-assets icons -----
# Plasmo normally generates icon{16,32,48,64,128}.plasmo.png via sharp,
# but if sharp is broken (network can't fetch prebuilt), use our pre-existing assets.
GEN_DIR="$EXT_DIR/.plasmo/gen-assets"
NEEDED_ICONS=(16 32 48 64 128)
need_icons=0
mkdir -p "$GEN_DIR"
for sz in "${NEEDED_ICONS[@]}"; do
  if [ ! -f "$GEN_DIR/icon${sz}.plasmo.png" ]; then need_icons=1; break; fi
done
if [ "$need_icons" = "1" ]; then
  echo "→ generating gen-assets/icon*.plasmo.png (16/32/48/64/128)..."
  SOURCE_PNG="$EXT_DIR/assets/icon-128.png"
  if [ ! -f "$SOURCE_PNG" ]; then
    echo "✗ $SOURCE_PNG missing"; exit 1
  fi
  # tiny Node.js script — no deps needed (uses zlib + Buffer)
  # Generate icons via node (separate file for clean quoting)
node "$(dirname "$0")/gen-plasmo-icons.mjs" "$SOURCE_PNG" "$GEN_DIR"
else
  echo "✓ gen-assets/ icons already present"
fi

# ----- 3. build -----
echo
echo "→ plasmo build --target=$TARGET"
(cd "$EXT_DIR" && npx plasmo build --target="$TARGET")

# 5. post-build：Plasmo 0.86 把 manifest name 字段搞空，这里补
bash "$ROOT/scripts/patch-node-modules.sh" p5 || true

BUILD_DIR="$EXT_DIR/build/$TARGET-prod"
echo
echo "============================================="
echo "  Build complete ✓"
echo "============================================="
ls -la "$BUILD_DIR/" 2>/dev/null | head -10
echo

# ----- 4. publish to dist/ (project root) -----
DIST_DIR="$ROOT/dist"
LATEST_DIR="$DIST_DIR/latest"
mkdir -p "$LATEST_DIR"

# Read version from manifest.json (or fallback to "0.0.0")
VERSION=$(python3 -c "import json; print(json.load(open('$BUILD_DIR/manifest.json')).get('version','0.0.0'))" 2>/dev/null || echo "0.0.0")
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
DATE_HUMAN=$(date "+%Y-%m-%d %H:%M:%S %Z")

# 4a. copy unpacked build to dist/latest/chrome-mv3-prod/
rm -rf "$LATEST_DIR/chrome-mv3-prod"
cp -r "$BUILD_DIR" "$LATEST_DIR/chrome-mv3-prod"
echo "✓ copied to $LATEST_DIR/chrome-mv3-prod/"

# 4b. always create a zip (Python-based, no zip CLI needed)
LATEST_ZIP="$LATEST_DIR/chrome-mv3-prod.zip"
python3 -c '
import sys, os, zipfile
src, out = sys.argv[1], sys.argv[2]
with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
    for root, dirs, files in os.walk(src):
        for f in files:
            full = os.path.join(root, f)
            rel = os.path.relpath(full, src)
            zf.write(full, rel)
' "$LATEST_DIR/chrome-mv3-prod" "$LATEST_ZIP"
ZIP_SIZE=$(du -h "$LATEST_ZIP" | cut -f1)
ZIP_SHA256=$(sha256sum "$LATEST_ZIP" | cut -d' ' -f1)
echo "✓ $LATEST_ZIP ($ZIP_SIZE, sha256:${ZIP_SHA256:0:12}…)"

# 4c. write build-info.txt
cat > "$LATEST_DIR/build-info.txt" <<INFO
YouTube AI Summary — Chrome Extension Build
==========================================

Built at:    $DATE_HUMAN
Version:     $VERSION
Target:      $TARGET
Manifest:    https://github.com/.../blob/main/extension/build/chrome-mv3-prod/manifest.json

Files
-----
Total files: $(find "$LATEST_DIR/chrome-mv3-prod" -type f | wc -l)
Zip size:    $ZIP_SIZE
Zip sha256:  $ZIP_SHA256

Files for Chrome Web Store
--------------------------
1. dist/latest/chrome-mv3-prod/      — unpacked (for inspection)
2. dist/latest/chrome-mv3-prod.zip   — upload THIS to CWS Developer Dashboard

Next steps
----------
1. Go to https://chrome.google.com/webstore/devconsole/
2. Pay one-time \$5 dev fee (first time only)
3. Click 'New Item' → upload dist/latest/chrome-mv3-prod.zip
4. Fill listing using docs/STORE_LISTING.md
5. Submit for review (typically 1-3 business days)
INFO
echo "✓ wrote $LATEST_DIR/build-info.txt"

# 4d. also archive to dist/archive/ (timestamped, never overwritten)
ARCHIVE_DIR="$DIST_DIR/archive"
mkdir -p "$ARCHIVE_DIR"
ARCHIVE_ZIP="$ARCHIVE_DIR/chrome-mv3-prod-v${VERSION}-${TIMESTAMP}.zip"
cp "$LATEST_ZIP" "$ARCHIVE_ZIP"
echo "✓ archived to $ARCHIVE_ZIP"

echo
echo "============================================="
echo "  Outputs"
echo "============================================="
echo "  Latest:    $LATEST_DIR/chrome-mv3-prod/"
echo "  Upload:    $LATEST_DIR/chrome-mv3-prod.zip   ($ZIP_SIZE)"
echo "  Archive:   $ARCHIVE_DIR/chrome-mv3-prod-v${VERSION}-${TIMESTAMP}.zip"
echo "  Info:      $LATEST_DIR/build-info.txt"
echo
echo "============================================="
echo "  Next steps"
echo "============================================="
echo "  1. Upload dist/latest/chrome-mv3-prod.zip to:"
echo "     https://chrome.google.com/webstore/devconsole/"
echo "  2. Pay one-time \$5 dev fee (first time only)"
echo "  3. Fill listing using docs/STORE_LISTING.md"
echo "  4. Submit for review (1-3 business days)"
echo
